version: "3.9"
services:
  api-gateway:
    build:
      context: moviesGo-api-gateway
      dockerfile: api-gateway.dockerfile
    environment:
      - PORT=:3000
      - AUTH_SVC_URL=auth-svc:50051
      - PRODUCT_SVC_URL=product-svc:50052
      - CART_SVC_URL=cart-svc:50055
      - ADMIN_AUTH_SVC_URL=admin-auth-svc:50054
    ports:
      - "3000:3000"
    depends_on:
      - auth-svc
      - product-svc
      - cart-svc
      - admin-auth-svc
    restart: always
    networks:
      - fullstack

  auth-svc:
    build:
      context: moviesGo-users-service
      dockerfile: user-service.dockerfile
    ports:
      - "50051:50051"
    environment:
      - PORT=:50051
      - DB_HOST=users-db
      - DB_NAME=users
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
    depends_on:
      - users-db
    restart: always
    networks:
      - fullstack

  product-svc:
    build:
      context: moviesGo-products-service
      dockerfile: products-service.dockerfile
    ports:
      - "50052:50052"
    environment:
      - PORT=:50052
      - DB_HOST=product-db
      - DB_NAME=products
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
    depends_on:
      - product-db
    restart: always
    networks:
      - fullstack

  cart-svc:
    build:
      context: moviesGo-carts-service
      dockerfile: carts-service.dockerfile
    ports:
      - "50055:50055"
    environment:
      - PORT=:50055
      - DB_HOST=carts-db
      - DB_NAME=carts
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - PRODUCT_SVC_URL=product-svc:50052
    depends_on:
      - carts-db
      - product-svc
    restart: always
    networks:
      - fullstack

  admin-auth-svc:
    build:
      context: moviesGo-admins-service
      dockerfile: admin-service.dockerfile
    ports:
      - "50054:50054"
    environment:
      - PORT=:50054
      - DB_HOST=admins-db
      - DB_NAME=admins
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
    depends_on:
      - admins-db
    restart: always
    networks:
      - fullstack

  users-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - fullstack

  product-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - fullstack

  carts-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=carts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - fullstack

  admins-db:
    image: postgres:latest
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=admins
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
