// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandkakkadi/moviesgo-user-service/pkg/api"
	"github.com/abhinandkakkadi/moviesgo-user-service/pkg/api/service"
	"github.com/abhinandkakkadi/moviesgo-user-service/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server,error) {

	// gormDB, err := db.ConnectDatabase(cfg)
	// if err != nil {
	// 	return nil,err
	// }

	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	// userServiceServer := service.NewUserServiceServer(userUseCase)
	userServiceServer := service.NewUserServiceServer(userUseCase)
	grpcServer, err := api.NewGRPCServer(cfg,userServiceServer)
	if err != nil {
		return &api.Server{},err
	}

	return grpcServer, nil
}
