// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: pkg/product/pb/product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenreRequest) Reset() {
	*x = GenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreRequest) ProtoMessage() {}

func (x *GenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreRequest.ProtoReflect.Descriptor instead.
func (*GenreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{0}
}

type GenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genreid   int64  `protobuf:"varint,1,opt,name=genreid,proto3" json:"genreid,omitempty"`
	Genrename string `protobuf:"bytes,2,opt,name=genrename,proto3" json:"genrename,omitempty"`
}

func (x *GenreResponse) Reset() {
	*x = GenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreResponse) ProtoMessage() {}

func (x *GenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreResponse.ProtoReflect.Descriptor instead.
func (*GenreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{1}
}

func (x *GenreResponse) GetGenreid() int64 {
	if x != nil {
		return x.Genreid
	}
	return 0
}

func (x *GenreResponse) GetGenrename() string {
	if x != nil {
		return x.Genrename
	}
	return ""
}

type AllGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allgenres []*GenreResponse `protobuf:"bytes,1,rep,name=allgenres,proto3" json:"allgenres,omitempty"`
}

func (x *AllGenreResponse) Reset() {
	*x = AllGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllGenreResponse) ProtoMessage() {}

func (x *AllGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllGenreResponse.ProtoReflect.Descriptor instead.
func (*AllGenreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{2}
}

func (x *AllGenreResponse) GetAllgenres() []*GenreResponse {
	if x != nil {
		return x.Allgenres
	}
	return nil
}

type StudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StudioRequest) Reset() {
	*x = StudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioRequest) ProtoMessage() {}

func (x *StudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioRequest.ProtoReflect.Descriptor instead.
func (*StudioRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{3}
}

type StudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Studioid   int64  `protobuf:"varint,1,opt,name=studioid,proto3" json:"studioid,omitempty"`
	Studioname string `protobuf:"bytes,2,opt,name=studioname,proto3" json:"studioname,omitempty"`
}

func (x *StudioResponse) Reset() {
	*x = StudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioResponse) ProtoMessage() {}

func (x *StudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioResponse.ProtoReflect.Descriptor instead.
func (*StudioResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{4}
}

func (x *StudioResponse) GetStudioid() int64 {
	if x != nil {
		return x.Studioid
	}
	return 0
}

func (x *StudioResponse) GetStudioname() string {
	if x != nil {
		return x.Studioname
	}
	return ""
}

type AllStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allstudios []*StudioResponse `protobuf:"bytes,1,rep,name=allstudios,proto3" json:"allstudios,omitempty"`
}

func (x *AllStudioResponse) Reset() {
	*x = AllStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStudioResponse) ProtoMessage() {}

func (x *AllStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStudioResponse.ProtoReflect.Descriptor instead.
func (*AllStudioResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{5}
}

func (x *AllStudioResponse) GetAllstudios() []*StudioResponse {
	if x != nil {
		return x.Allstudios
	}
	return nil
}

type ShowProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Count int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ShowProductRequest) Reset() {
	*x = ShowProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductRequest) ProtoMessage() {}

func (x *ShowProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductRequest.ProtoReflect.Descriptor instead.
func (*ShowProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{6}
}

func (x *ShowProductRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShowProductRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ShowProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid int64  `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
	Moviename string `protobuf:"bytes,2,opt,name=moviename,proto3" json:"moviename,omitempty"`
	Sku       string `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Genre     string `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Language  string `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Price     string `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity  int64  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ShowProductResponse) Reset() {
	*x = ShowProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductResponse) ProtoMessage() {}

func (x *ShowProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductResponse.ProtoReflect.Descriptor instead.
func (*ShowProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{7}
}

func (x *ShowProductResponse) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

func (x *ShowProductResponse) GetMoviename() string {
	if x != nil {
		return x.Moviename
	}
	return ""
}

func (x *ShowProductResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShowProductResponse) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ShowProductResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ShowProductResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ShowProductResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ShowAllProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productsbrief []*ShowProductResponse `protobuf:"bytes,1,rep,name=productsbrief,proto3" json:"productsbrief,omitempty"`
}

func (x *ShowAllProductResponse) Reset() {
	*x = ShowAllProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowAllProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAllProductResponse) ProtoMessage() {}

func (x *ShowAllProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAllProductResponse.ProtoReflect.Descriptor instead.
func (*ShowAllProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{8}
}

func (x *ShowAllProductResponse) GetProductsbrief() []*ShowProductResponse {
	if x != nil {
		return x.Productsbrief
	}
	return nil
}

type AddProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moviename          string `protobuf:"bytes,1,opt,name=moviename,proto3" json:"moviename,omitempty"`
	Genreid            int64  `protobuf:"varint,2,opt,name=genreid,proto3" json:"genreid,omitempty"`
	Releaseyear        string `protobuf:"bytes,3,opt,name=releaseyear,proto3" json:"releaseyear,omitempty"`
	Format             string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Director           string `protobuf:"bytes,5,opt,name=director,proto3" json:"director,omitempty"`
	Productdescription string `protobuf:"bytes,6,opt,name=productdescription,proto3" json:"productdescription,omitempty"`
	Runtime            int64  `protobuf:"varint,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Language           string `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Studioid           int64  `protobuf:"varint,9,opt,name=studioid,proto3" json:"studioid,omitempty"`
	Quantity           int64  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price              int64  `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{9}
}

func (x *AddProductRequest) GetMoviename() string {
	if x != nil {
		return x.Moviename
	}
	return ""
}

func (x *AddProductRequest) GetGenreid() int64 {
	if x != nil {
		return x.Genreid
	}
	return 0
}

func (x *AddProductRequest) GetReleaseyear() string {
	if x != nil {
		return x.Releaseyear
	}
	return ""
}

func (x *AddProductRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AddProductRequest) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *AddProductRequest) GetProductdescription() string {
	if x != nil {
		return x.Productdescription
	}
	return ""
}

func (x *AddProductRequest) GetRuntime() int64 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *AddProductRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AddProductRequest) GetStudioid() int64 {
	if x != nil {
		return x.Studioid
	}
	return 0
}

func (x *AddProductRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{10}
}

func (x *AddProductResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_pkg_product_pb_product_proto protoreflect.FileDescriptor

var file_pkg_product_pb_product_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x48, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x09, 0x61, 0x6c, 0x6c, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x0e, 0x53,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x74, 0x75, 0x64, 0x69, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x11, 0x41, 0x6c, 0x6c,
	0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37,
	0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x61, 0x6c, 0x6c,
	0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x77, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x77,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x14, 0x0a,
	0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x5c, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f,
	0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x62, 0x72, 0x69, 0x65, 0x66, 0x22,
	0xd5, 0x02, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x79, 0x65, 0x61, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x75,
	0x64, 0x69, 0x6f, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xbd, 0x02, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x77,
	0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_product_pb_product_proto_rawDescOnce sync.Once
	file_pkg_product_pb_product_proto_rawDescData = file_pkg_product_pb_product_proto_rawDesc
)

func file_pkg_product_pb_product_proto_rawDescGZIP() []byte {
	file_pkg_product_pb_product_proto_rawDescOnce.Do(func() {
		file_pkg_product_pb_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_product_pb_product_proto_rawDescData)
	})
	return file_pkg_product_pb_product_proto_rawDescData
}

var file_pkg_product_pb_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_product_pb_product_proto_goTypes = []interface{}{
	(*GenreRequest)(nil),           // 0: product.GenreRequest
	(*GenreResponse)(nil),          // 1: product.GenreResponse
	(*AllGenreResponse)(nil),       // 2: product.AllGenreResponse
	(*StudioRequest)(nil),          // 3: product.StudioRequest
	(*StudioResponse)(nil),         // 4: product.StudioResponse
	(*AllStudioResponse)(nil),      // 5: product.AllStudioResponse
	(*ShowProductRequest)(nil),     // 6: product.ShowProductRequest
	(*ShowProductResponse)(nil),    // 7: product.ShowProductResponse
	(*ShowAllProductResponse)(nil), // 8: product.ShowAllProductResponse
	(*AddProductRequest)(nil),      // 9: product.AddProductRequest
	(*AddProductResponse)(nil),     // 10: product.AddProductResponse
}
var file_pkg_product_pb_product_proto_depIdxs = []int32{
	1,  // 0: product.AllGenreResponse.allgenres:type_name -> product.GenreResponse
	4,  // 1: product.AllStudioResponse.allstudios:type_name -> product.StudioResponse
	7,  // 2: product.ShowAllProductResponse.productsbrief:type_name -> product.ShowProductResponse
	6,  // 3: product.ProductService.ShowAllProducts:input_type -> product.ShowProductRequest
	9,  // 4: product.ProductService.AddProduct:input_type -> product.AddProductRequest
	0,  // 5: product.ProductService.GetGenreDetails:input_type -> product.GenreRequest
	3,  // 6: product.ProductService.GetStudioDetails:input_type -> product.StudioRequest
	8,  // 7: product.ProductService.ShowAllProducts:output_type -> product.ShowAllProductResponse
	10, // 8: product.ProductService.AddProduct:output_type -> product.AddProductResponse
	2,  // 9: product.ProductService.GetGenreDetails:output_type -> product.AllGenreResponse
	5,  // 10: product.ProductService.GetStudioDetails:output_type -> product.AllStudioResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_product_pb_product_proto_init() }
func file_pkg_product_pb_product_proto_init() {
	if File_pkg_product_pb_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_product_pb_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowAllProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_product_pb_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_product_pb_product_proto_goTypes,
		DependencyIndexes: file_pkg_product_pb_product_proto_depIdxs,
		MessageInfos:      file_pkg_product_pb_product_proto_msgTypes,
	}.Build()
	File_pkg_product_pb_product_proto = out.File
	file_pkg_product_pb_product_proto_rawDesc = nil
	file_pkg_product_pb_product_proto_goTypes = nil
	file_pkg_product_pb_product_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	ShowAllProducts(ctx context.Context, in *ShowProductRequest, opts ...grpc.CallOption) (*ShowAllProductResponse, error)
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	GetGenreDetails(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*AllGenreResponse, error)
	GetStudioDetails(ctx context.Context, in *StudioRequest, opts ...grpc.CallOption) (*AllStudioResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) ShowAllProducts(ctx context.Context, in *ShowProductRequest, opts ...grpc.CallOption) (*ShowAllProductResponse, error) {
	out := new(ShowAllProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/ShowAllProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetGenreDetails(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*AllGenreResponse, error) {
	out := new(AllGenreResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetGenreDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetStudioDetails(ctx context.Context, in *StudioRequest, opts ...grpc.CallOption) (*AllStudioResponse, error) {
	out := new(AllStudioResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetStudioDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	ShowAllProducts(context.Context, *ShowProductRequest) (*ShowAllProductResponse, error)
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	GetGenreDetails(context.Context, *GenreRequest) (*AllGenreResponse, error)
	GetStudioDetails(context.Context, *StudioRequest) (*AllStudioResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) ShowAllProducts(context.Context, *ShowProductRequest) (*ShowAllProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAllProducts not implemented")
}
func (*UnimplementedProductServiceServer) AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetGenreDetails(context.Context, *GenreRequest) (*AllGenreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenreDetails not implemented")
}
func (*UnimplementedProductServiceServer) GetStudioDetails(context.Context, *StudioRequest) (*AllStudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudioDetails not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_ShowAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ShowAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ShowAllProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ShowAllProducts(ctx, req.(*ShowProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetGenreDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetGenreDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetGenreDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetGenreDetails(ctx, req.(*GenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetStudioDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetStudioDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetStudioDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetStudioDetails(ctx, req.(*StudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowAllProducts",
			Handler:    _ProductService_ShowAllProducts_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _ProductService_AddProduct_Handler,
		},
		{
			MethodName: "GetGenreDetails",
			Handler:    _ProductService_GetGenreDetails_Handler,
		},
		{
			MethodName: "GetStudioDetails",
			Handler:    _ProductService_GetStudioDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/product/pb/product.proto",
}
