// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/api"
	"github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/api/handler"
	"github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/config"
	interfaces "github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/repository/interface"
	"github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/client"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, interfaces.ProductRepository, error) {

	userClient := client.NewUserClient(cfg)

	userHandler := handler.NewUserHandler(userClient)
	// productHandler := handler.NewProductHandler(productUseCase)
	// adminHandler := handler.NewAdminHandler(adminUseCase)
	// cartHandler := handler.NewCartHandler(cartuseCase)
	// orderHandler := handler.NewOrderHandler(orderUseCase)

	serverHTTP := http.NewServerHTTP(userHandler, productHandler, adminHandler, cartHandler, orderHandler)

	return serverHTTP, nil
}
