// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/api"
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/api/handler"
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/config"
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/client"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP,error) {

	userClient := client.NewUserClient(cfg)

	userHandler := handler.NewUserHandler(userClient)
	// productHandler := handler.NewProductHandler(productUseCase)
	// adminHandler := handler.NewAdminHandler(adminUseCase)
	// cartHandler := handler.NewCartHandler(cartuseCase)
	// orderHandler := handler.NewOrderHandler(orderUseCase)

	serverHTTP := http.NewServerHTTP(userHandler)

	return serverHTTP, nil
}
