// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/api"
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/api/handler"
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/client"
	"github.com/abhinandkakkadi/moviesgo-api-gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {

	userClient := client.NewUserClient(cfg)
	userHandler := handler.NewUserHandler(userClient)

	adminClient := client.NewAdminClient(cfg)
	adminHandler := handler.NewAdminHandler(adminClient)

	productClient := client.NewProductClient(cfg)
	productHandler := handler.NewProductHandler(productClient)

	// cartHandler := handler.NewCartHandler(cartuseCase)
	// orderHandler := handler.NewOrderHandler(orderUseCase)

	serverHTTP := http.NewServerHTTP(userHandler,adminHandler,userClient,adminClient,productHandler)

	return serverHTTP, nil
}
