// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/api"
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/api/service"
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/client"
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/config"
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/db"
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/repository"
	"github.com/abhinandkakkadi/moviesgo-carts-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {

	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}

	cartRepository := repository.NewCartRepository(gormDB)
	productClient := client.NewProductClient(cfg)
	cartUseCase := usecase.NewCartUseCase(cartRepository, productClient)

	cartServiceServer := service.NewCartServiceServer(cartUseCase)
	grpcServer, err := api.NewGRPCServer(cfg, cartServiceServer)

	if err != nil {
		return &api.Server{}, err
	}

	return grpcServer, nil

}
