// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: pkg/product/pb/product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductIDS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid int64 `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
}

func (x *ProductIDS) Reset() {
	*x = ProductIDS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductIDS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIDS) ProtoMessage() {}

func (x *ProductIDS) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIDS.ProtoReflect.Descriptor instead.
func (*ProductIDS) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductIDS) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

type ProductIDSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allproductids []*ProductIDS `protobuf:"bytes,1,rep,name=allproductids,proto3" json:"allproductids,omitempty"`
}

func (x *ProductIDSRequest) Reset() {
	*x = ProductIDSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductIDSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIDSRequest) ProtoMessage() {}

func (x *ProductIDSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIDSRequest.ProtoReflect.Descriptor instead.
func (*ProductIDSRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductIDSRequest) GetAllproductids() []*ProductIDS {
	if x != nil {
		return x.Allproductids
	}
	return nil
}

type ProductNameWithID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid   int64  `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
	Productname string `protobuf:"bytes,2,opt,name=productname,proto3" json:"productname,omitempty"`
}

func (x *ProductNameWithID) Reset() {
	*x = ProductNameWithID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductNameWithID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductNameWithID) ProtoMessage() {}

func (x *ProductNameWithID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductNameWithID.ProtoReflect.Descriptor instead.
func (*ProductNameWithID) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductNameWithID) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

func (x *ProductNameWithID) GetProductname() string {
	if x != nil {
		return x.Productname
	}
	return ""
}

type ProductNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productswithid []*ProductNameWithID `protobuf:"bytes,1,rep,name=productswithid,proto3" json:"productswithid,omitempty"`
}

func (x *ProductNamesResponse) Reset() {
	*x = ProductNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductNamesResponse) ProtoMessage() {}

func (x *ProductNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductNamesResponse.ProtoReflect.Descriptor instead.
func (*ProductNamesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductNamesResponse) GetProductswithid() []*ProductNameWithID {
	if x != nil {
		return x.Productswithid
	}
	return nil
}

type ProductPriceFromIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid int64 `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
}

func (x *ProductPriceFromIDRequest) Reset() {
	*x = ProductPriceFromIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPriceFromIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceFromIDRequest) ProtoMessage() {}

func (x *ProductPriceFromIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceFromIDRequest.ProtoReflect.Descriptor instead.
func (*ProductPriceFromIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductPriceFromIDRequest) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

type ProductPriceFromIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ProductPriceFromIDResponse) Reset() {
	*x = ProductPriceFromIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPriceFromIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceFromIDResponse) ProtoMessage() {}

func (x *ProductPriceFromIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceFromIDResponse.ProtoReflect.Descriptor instead.
func (*ProductPriceFromIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductPriceFromIDResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProductExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid int64 `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
}

func (x *ProductExistRequest) Reset() {
	*x = ProductExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductExistRequest) ProtoMessage() {}

func (x *ProductExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductExistRequest.ProtoReflect.Descriptor instead.
func (*ProductExistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductExistRequest) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

type ProductExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prouctexist bool `protobuf:"varint,2,opt,name=prouctexist,proto3" json:"prouctexist,omitempty"`
}

func (x *ProductExistResponse) Reset() {
	*x = ProductExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductExistResponse) ProtoMessage() {}

func (x *ProductExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductExistResponse.ProtoReflect.Descriptor instead.
func (*ProductExistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{7}
}

func (x *ProductExistResponse) GetProuctexist() bool {
	if x != nil {
		return x.Prouctexist
	}
	return false
}

type ProductNameFromIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid int64 `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
}

func (x *ProductNameFromIDRequest) Reset() {
	*x = ProductNameFromIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductNameFromIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductNameFromIDRequest) ProtoMessage() {}

func (x *ProductNameFromIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductNameFromIDRequest.ProtoReflect.Descriptor instead.
func (*ProductNameFromIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{8}
}

func (x *ProductNameFromIDRequest) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

type ProductNameFromIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productname string `protobuf:"bytes,1,opt,name=productname,proto3" json:"productname,omitempty"`
}

func (x *ProductNameFromIDResponse) Reset() {
	*x = ProductNameFromIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductNameFromIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductNameFromIDResponse) ProtoMessage() {}

func (x *ProductNameFromIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductNameFromIDResponse.ProtoReflect.Descriptor instead.
func (*ProductNameFromIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductNameFromIDResponse) GetProductname() string {
	if x != nil {
		return x.Productname
	}
	return ""
}

type GenreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenreRequest) Reset() {
	*x = GenreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreRequest) ProtoMessage() {}

func (x *GenreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreRequest.ProtoReflect.Descriptor instead.
func (*GenreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{10}
}

type GenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genreid   int64  `protobuf:"varint,1,opt,name=genreid,proto3" json:"genreid,omitempty"`
	Genrename string `protobuf:"bytes,2,opt,name=genrename,proto3" json:"genrename,omitempty"`
}

func (x *GenreResponse) Reset() {
	*x = GenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreResponse) ProtoMessage() {}

func (x *GenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreResponse.ProtoReflect.Descriptor instead.
func (*GenreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{11}
}

func (x *GenreResponse) GetGenreid() int64 {
	if x != nil {
		return x.Genreid
	}
	return 0
}

func (x *GenreResponse) GetGenrename() string {
	if x != nil {
		return x.Genrename
	}
	return ""
}

type AllGenreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allgenres []*GenreResponse `protobuf:"bytes,1,rep,name=allgenres,proto3" json:"allgenres,omitempty"`
}

func (x *AllGenreResponse) Reset() {
	*x = AllGenreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllGenreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllGenreResponse) ProtoMessage() {}

func (x *AllGenreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllGenreResponse.ProtoReflect.Descriptor instead.
func (*AllGenreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{12}
}

func (x *AllGenreResponse) GetAllgenres() []*GenreResponse {
	if x != nil {
		return x.Allgenres
	}
	return nil
}

type StudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StudioRequest) Reset() {
	*x = StudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioRequest) ProtoMessage() {}

func (x *StudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioRequest.ProtoReflect.Descriptor instead.
func (*StudioRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{13}
}

type StudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Studioid   int64  `protobuf:"varint,1,opt,name=studioid,proto3" json:"studioid,omitempty"`
	Studioname string `protobuf:"bytes,2,opt,name=studioname,proto3" json:"studioname,omitempty"`
}

func (x *StudioResponse) Reset() {
	*x = StudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudioResponse) ProtoMessage() {}

func (x *StudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudioResponse.ProtoReflect.Descriptor instead.
func (*StudioResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{14}
}

func (x *StudioResponse) GetStudioid() int64 {
	if x != nil {
		return x.Studioid
	}
	return 0
}

func (x *StudioResponse) GetStudioname() string {
	if x != nil {
		return x.Studioname
	}
	return ""
}

type AllStudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allstudios []*StudioResponse `protobuf:"bytes,1,rep,name=allstudios,proto3" json:"allstudios,omitempty"`
}

func (x *AllStudioResponse) Reset() {
	*x = AllStudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllStudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStudioResponse) ProtoMessage() {}

func (x *AllStudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStudioResponse.ProtoReflect.Descriptor instead.
func (*AllStudioResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{15}
}

func (x *AllStudioResponse) GetAllstudios() []*StudioResponse {
	if x != nil {
		return x.Allstudios
	}
	return nil
}

type ShowProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Count int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ShowProductRequest) Reset() {
	*x = ShowProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductRequest) ProtoMessage() {}

func (x *ShowProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductRequest.ProtoReflect.Descriptor instead.
func (*ShowProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{16}
}

func (x *ShowProductRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ShowProductRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ShowProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productid int64  `protobuf:"varint,1,opt,name=productid,proto3" json:"productid,omitempty"`
	Moviename string `protobuf:"bytes,2,opt,name=moviename,proto3" json:"moviename,omitempty"`
	Sku       string `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Genre     string `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Language  string `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Price     string `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity  int64  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ShowProductResponse) Reset() {
	*x = ShowProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowProductResponse) ProtoMessage() {}

func (x *ShowProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowProductResponse.ProtoReflect.Descriptor instead.
func (*ShowProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{17}
}

func (x *ShowProductResponse) GetProductid() int64 {
	if x != nil {
		return x.Productid
	}
	return 0
}

func (x *ShowProductResponse) GetMoviename() string {
	if x != nil {
		return x.Moviename
	}
	return ""
}

func (x *ShowProductResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShowProductResponse) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ShowProductResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ShowProductResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ShowProductResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ShowAllProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Productsbrief []*ShowProductResponse `protobuf:"bytes,1,rep,name=productsbrief,proto3" json:"productsbrief,omitempty"`
}

func (x *ShowAllProductResponse) Reset() {
	*x = ShowAllProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowAllProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAllProductResponse) ProtoMessage() {}

func (x *ShowAllProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAllProductResponse.ProtoReflect.Descriptor instead.
func (*ShowAllProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{18}
}

func (x *ShowAllProductResponse) GetProductsbrief() []*ShowProductResponse {
	if x != nil {
		return x.Productsbrief
	}
	return nil
}

type AddProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Moviename          string `protobuf:"bytes,1,opt,name=moviename,proto3" json:"moviename,omitempty"`
	Genreid            int64  `protobuf:"varint,2,opt,name=genreid,proto3" json:"genreid,omitempty"`
	Releaseyear        string `protobuf:"bytes,3,opt,name=releaseyear,proto3" json:"releaseyear,omitempty"`
	Format             string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Director           string `protobuf:"bytes,5,opt,name=director,proto3" json:"director,omitempty"`
	Productdescription string `protobuf:"bytes,6,opt,name=productdescription,proto3" json:"productdescription,omitempty"`
	Runtime            int64  `protobuf:"varint,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Language           string `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Studioid           int64  `protobuf:"varint,9,opt,name=studioid,proto3" json:"studioid,omitempty"`
	Quantity           int64  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price              int64  `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{19}
}

func (x *AddProductRequest) GetMoviename() string {
	if x != nil {
		return x.Moviename
	}
	return ""
}

func (x *AddProductRequest) GetGenreid() int64 {
	if x != nil {
		return x.Genreid
	}
	return 0
}

func (x *AddProductRequest) GetReleaseyear() string {
	if x != nil {
		return x.Releaseyear
	}
	return ""
}

func (x *AddProductRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AddProductRequest) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *AddProductRequest) GetProductdescription() string {
	if x != nil {
		return x.Productdescription
	}
	return ""
}

func (x *AddProductRequest) GetRuntime() int64 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *AddProductRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AddProductRequest) GetStudioid() int64 {
	if x != nil {
		return x.Studioid
	}
	return 0
}

func (x *AddProductRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_product_pb_product_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_product_pb_product_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_product_pb_product_proto_rawDescGZIP(), []int{20}
}

func (x *AddProductResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_pkg_product_pb_product_proto protoreflect.FileDescriptor

var file_pkg_product_pb_product_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x2a, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x44, 0x53, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44,
	0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x44, 0x53, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x64, 0x73, 0x22, 0x53, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x57, 0x69, 0x74, 0x68, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x77, 0x69, 0x74, 0x68,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x49, 0x44, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x77, 0x69,
	0x74, 0x68, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x22,
	0x32, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x22, 0x33, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x75, 0x63, 0x74, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x75, 0x63, 0x74, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x22, 0x38, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x19,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x0d, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x65, 0x6e, 0x72, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x09, 0x61, 0x6c, 0x6c, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4c, 0x0a, 0x0e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a,
	0x11, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0a, 0x61, 0x6c, 0x6c, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x53,
	0x68, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x13,
	0x53, 0x68, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b,
	0x75, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x5c, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x62, 0x72, 0x69, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2e, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x62, 0x72,
	0x69, 0x65, 0x66, 0x22, 0xd5, 0x02, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x79, 0x65, 0x61, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x79,
	0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xaf, 0x05, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0f,
	0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x47, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x6c, 0x6c,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x10, 0x44, 0x6f, 0x65,
	0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x49, 0x44, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x58, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x44, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_product_pb_product_proto_rawDescOnce sync.Once
	file_pkg_product_pb_product_proto_rawDescData = file_pkg_product_pb_product_proto_rawDesc
)

func file_pkg_product_pb_product_proto_rawDescGZIP() []byte {
	file_pkg_product_pb_product_proto_rawDescOnce.Do(func() {
		file_pkg_product_pb_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_product_pb_product_proto_rawDescData)
	})
	return file_pkg_product_pb_product_proto_rawDescData
}

var file_pkg_product_pb_product_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_product_pb_product_proto_goTypes = []interface{}{
	(*ProductIDS)(nil),                 // 0: product.ProductIDS
	(*ProductIDSRequest)(nil),          // 1: product.ProductIDSRequest
	(*ProductNameWithID)(nil),          // 2: product.ProductNameWithID
	(*ProductNamesResponse)(nil),       // 3: product.ProductNamesResponse
	(*ProductPriceFromIDRequest)(nil),  // 4: product.ProductPriceFromIDRequest
	(*ProductPriceFromIDResponse)(nil), // 5: product.ProductPriceFromIDResponse
	(*ProductExistRequest)(nil),        // 6: product.ProductExistRequest
	(*ProductExistResponse)(nil),       // 7: product.ProductExistResponse
	(*ProductNameFromIDRequest)(nil),   // 8: product.ProductNameFromIDRequest
	(*ProductNameFromIDResponse)(nil),  // 9: product.ProductNameFromIDResponse
	(*GenreRequest)(nil),               // 10: product.GenreRequest
	(*GenreResponse)(nil),              // 11: product.GenreResponse
	(*AllGenreResponse)(nil),           // 12: product.AllGenreResponse
	(*StudioRequest)(nil),              // 13: product.StudioRequest
	(*StudioResponse)(nil),             // 14: product.StudioResponse
	(*AllStudioResponse)(nil),          // 15: product.AllStudioResponse
	(*ShowProductRequest)(nil),         // 16: product.ShowProductRequest
	(*ShowProductResponse)(nil),        // 17: product.ShowProductResponse
	(*ShowAllProductResponse)(nil),     // 18: product.ShowAllProductResponse
	(*AddProductRequest)(nil),          // 19: product.AddProductRequest
	(*AddProductResponse)(nil),         // 20: product.AddProductResponse
}
var file_pkg_product_pb_product_proto_depIdxs = []int32{
	0,  // 0: product.ProductIDSRequest.allproductids:type_name -> product.ProductIDS
	2,  // 1: product.ProductNamesResponse.productswithid:type_name -> product.ProductNameWithID
	11, // 2: product.AllGenreResponse.allgenres:type_name -> product.GenreResponse
	14, // 3: product.AllStudioResponse.allstudios:type_name -> product.StudioResponse
	17, // 4: product.ShowAllProductResponse.productsbrief:type_name -> product.ShowProductResponse
	16, // 5: product.ProductService.ShowAllProducts:input_type -> product.ShowProductRequest
	19, // 6: product.ProductService.AddProduct:input_type -> product.AddProductRequest
	10, // 7: product.ProductService.GetGenreDetails:input_type -> product.GenreRequest
	13, // 8: product.ProductService.GetStudioDetails:input_type -> product.StudioRequest
	6,  // 9: product.ProductService.DoesProductExist:input_type -> product.ProductExistRequest
	8,  // 10: product.ProductService.GetProductNameFromID:input_type -> product.ProductNameFromIDRequest
	4,  // 11: product.ProductService.GetProductPriceFromID:input_type -> product.ProductPriceFromIDRequest
	1,  // 12: product.ProductService.GetCartProductsNameFromID:input_type -> product.ProductIDSRequest
	18, // 13: product.ProductService.ShowAllProducts:output_type -> product.ShowAllProductResponse
	20, // 14: product.ProductService.AddProduct:output_type -> product.AddProductResponse
	12, // 15: product.ProductService.GetGenreDetails:output_type -> product.AllGenreResponse
	15, // 16: product.ProductService.GetStudioDetails:output_type -> product.AllStudioResponse
	7,  // 17: product.ProductService.DoesProductExist:output_type -> product.ProductExistResponse
	9,  // 18: product.ProductService.GetProductNameFromID:output_type -> product.ProductNameFromIDResponse
	5,  // 19: product.ProductService.GetProductPriceFromID:output_type -> product.ProductPriceFromIDResponse
	3,  // 20: product.ProductService.GetCartProductsNameFromID:output_type -> product.ProductNamesResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_product_pb_product_proto_init() }
func file_pkg_product_pb_product_proto_init() {
	if File_pkg_product_pb_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_product_pb_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductIDS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductIDSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductNameWithID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPriceFromIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPriceFromIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductNameFromIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductNameFromIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllGenreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllStudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowAllProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_product_pb_product_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_product_pb_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_product_pb_product_proto_goTypes,
		DependencyIndexes: file_pkg_product_pb_product_proto_depIdxs,
		MessageInfos:      file_pkg_product_pb_product_proto_msgTypes,
	}.Build()
	File_pkg_product_pb_product_proto = out.File
	file_pkg_product_pb_product_proto_rawDesc = nil
	file_pkg_product_pb_product_proto_goTypes = nil
	file_pkg_product_pb_product_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	ShowAllProducts(ctx context.Context, in *ShowProductRequest, opts ...grpc.CallOption) (*ShowAllProductResponse, error)
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	GetGenreDetails(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*AllGenreResponse, error)
	GetStudioDetails(ctx context.Context, in *StudioRequest, opts ...grpc.CallOption) (*AllStudioResponse, error)
	DoesProductExist(ctx context.Context, in *ProductExistRequest, opts ...grpc.CallOption) (*ProductExistResponse, error)
	GetProductNameFromID(ctx context.Context, in *ProductNameFromIDRequest, opts ...grpc.CallOption) (*ProductNameFromIDResponse, error)
	GetProductPriceFromID(ctx context.Context, in *ProductPriceFromIDRequest, opts ...grpc.CallOption) (*ProductPriceFromIDResponse, error)
	GetCartProductsNameFromID(ctx context.Context, in *ProductIDSRequest, opts ...grpc.CallOption) (*ProductNamesResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) ShowAllProducts(ctx context.Context, in *ShowProductRequest, opts ...grpc.CallOption) (*ShowAllProductResponse, error) {
	out := new(ShowAllProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/ShowAllProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetGenreDetails(ctx context.Context, in *GenreRequest, opts ...grpc.CallOption) (*AllGenreResponse, error) {
	out := new(AllGenreResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetGenreDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetStudioDetails(ctx context.Context, in *StudioRequest, opts ...grpc.CallOption) (*AllStudioResponse, error) {
	out := new(AllStudioResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetStudioDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DoesProductExist(ctx context.Context, in *ProductExistRequest, opts ...grpc.CallOption) (*ProductExistResponse, error) {
	out := new(ProductExistResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/DoesProductExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductNameFromID(ctx context.Context, in *ProductNameFromIDRequest, opts ...grpc.CallOption) (*ProductNameFromIDResponse, error) {
	out := new(ProductNameFromIDResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductNameFromID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductPriceFromID(ctx context.Context, in *ProductPriceFromIDRequest, opts ...grpc.CallOption) (*ProductPriceFromIDResponse, error) {
	out := new(ProductPriceFromIDResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductPriceFromID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetCartProductsNameFromID(ctx context.Context, in *ProductIDSRequest, opts ...grpc.CallOption) (*ProductNamesResponse, error) {
	out := new(ProductNamesResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetCartProductsNameFromID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	ShowAllProducts(context.Context, *ShowProductRequest) (*ShowAllProductResponse, error)
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	GetGenreDetails(context.Context, *GenreRequest) (*AllGenreResponse, error)
	GetStudioDetails(context.Context, *StudioRequest) (*AllStudioResponse, error)
	DoesProductExist(context.Context, *ProductExistRequest) (*ProductExistResponse, error)
	GetProductNameFromID(context.Context, *ProductNameFromIDRequest) (*ProductNameFromIDResponse, error)
	GetProductPriceFromID(context.Context, *ProductPriceFromIDRequest) (*ProductPriceFromIDResponse, error)
	GetCartProductsNameFromID(context.Context, *ProductIDSRequest) (*ProductNamesResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) ShowAllProducts(context.Context, *ShowProductRequest) (*ShowAllProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAllProducts not implemented")
}
func (*UnimplementedProductServiceServer) AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetGenreDetails(context.Context, *GenreRequest) (*AllGenreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenreDetails not implemented")
}
func (*UnimplementedProductServiceServer) GetStudioDetails(context.Context, *StudioRequest) (*AllStudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudioDetails not implemented")
}
func (*UnimplementedProductServiceServer) DoesProductExist(context.Context, *ProductExistRequest) (*ProductExistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoesProductExist not implemented")
}
func (*UnimplementedProductServiceServer) GetProductNameFromID(context.Context, *ProductNameFromIDRequest) (*ProductNameFromIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductNameFromID not implemented")
}
func (*UnimplementedProductServiceServer) GetProductPriceFromID(context.Context, *ProductPriceFromIDRequest) (*ProductPriceFromIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductPriceFromID not implemented")
}
func (*UnimplementedProductServiceServer) GetCartProductsNameFromID(context.Context, *ProductIDSRequest) (*ProductNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartProductsNameFromID not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_ShowAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ShowAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ShowAllProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ShowAllProducts(ctx, req.(*ShowProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetGenreDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetGenreDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetGenreDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetGenreDetails(ctx, req.(*GenreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetStudioDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetStudioDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetStudioDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetStudioDetails(ctx, req.(*StudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DoesProductExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DoesProductExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DoesProductExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DoesProductExist(ctx, req.(*ProductExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductNameFromID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductNameFromIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductNameFromID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductNameFromID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductNameFromID(ctx, req.(*ProductNameFromIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductPriceFromID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductPriceFromIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductPriceFromID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductPriceFromID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductPriceFromID(ctx, req.(*ProductPriceFromIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetCartProductsNameFromID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductIDSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetCartProductsNameFromID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetCartProductsNameFromID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetCartProductsNameFromID(ctx, req.(*ProductIDSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowAllProducts",
			Handler:    _ProductService_ShowAllProducts_Handler,
		},
		{
			MethodName: "AddProduct",
			Handler:    _ProductService_AddProduct_Handler,
		},
		{
			MethodName: "GetGenreDetails",
			Handler:    _ProductService_GetGenreDetails_Handler,
		},
		{
			MethodName: "GetStudioDetails",
			Handler:    _ProductService_GetStudioDetails_Handler,
		},
		{
			MethodName: "DoesProductExist",
			Handler:    _ProductService_DoesProductExist_Handler,
		},
		{
			MethodName: "GetProductNameFromID",
			Handler:    _ProductService_GetProductNameFromID_Handler,
		},
		{
			MethodName: "GetProductPriceFromID",
			Handler:    _ProductService_GetProductPriceFromID_Handler,
		},
		{
			MethodName: "GetCartProductsNameFromID",
			Handler:    _ProductService_GetCartProductsNameFromID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/product/pb/product.proto",
}
