// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/abhinandkakkadi/moviesgo-admin-service/pkg/api"
	"github.com/abhinandkakkadi/moviesgo-admin-service/pkg/api/service"
	"github.com/abhinandkakkadi/moviesgo-admin-service/pkg/config"
	"github.com/abhinandkakkadi/moviesgo-admin-service/pkg/db"
	"github.com/abhinandkakkadi/moviesgo-admin-service/pkg/repository"
	"github.com/abhinandkakkadi/moviesgo-admin-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {

	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}

	adminRepository := repository.NewAdminRepository(gormDB)
	adminUseCase := usecase.NewAdminUseCase(adminRepository)

	adminServiceServer := service.NewAdminServiceServer(adminUseCase)
	grpcServer, err := api.NewGRPCServer(cfg, adminServiceServer)

	if err != nil {
		return &api.Server{}, err
	}

	return grpcServer, nil

}
